### ISSUE TITLE
[이슈] 깃헙 액션 테스트가 PR 커밋에서가 아닌 Base 브랜치 소스로 돌아가는 이슈

### ISSUE THREAD

**Issue by x-0o0** [ku-ring/app-ios-v2#84]
## 이슈 설명
깃헙 액션 테스트가 PR 커밋에서가 아닌 Base 브랜치 소스로 돌아가서 실제 PR 의 코드가 테스트 되지 않고 있음

## 재현방법
1. base 브랜치에 테스트 실패하는 커밋 푸시
2. base 브랜치로 머지하는 새로운 PR 생성
3. PR 에서 테스트 실패 해결
4. 깃헙 액션 실행
5. 결과 확인

## 기대결과
PR 에서 테스트 이슈가 해결 되었으므로 깃헙 액션이 성공해야함

## 실제 에러 내용
#83 에서 확인 가능

## 버전 정보

| 플랫폼 | 버전 |
| --- | --- |
| 쿠링 앱 | 2.0.0 |
| iOS | 17.0 |
| Xcode | 15.0.1 |

**Comment by x-0o0** [comment]
깃헙액션에서 커밋 중 존재하지 않는 커밋 해시값이 존재해서 알아보던 중 다음과 같은 글 발견
https://stackoverflow.com/a/62335935

> You are experiencing this because your workflow is running on `pull_request` events. During those events, `GITHUB_REF` is a merge commit from the head branch to the base. The intention of this is to run CI against the merge commit to check it passes before it's actually merged.
> 
> If you don't want the merge commit and want to checkout the head commit instead, you have to pass the HEAD's sha as ref to the checkout. You can change the checkout as follows (taken from [this example](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit)).

[요약] 
`pull_request` 이벤트에서 `GITHUB_REF` 는 HEAD 에서 base 브랜치로 병합된 커밋. 즉, 실제로 머지가 되었을 때 문제가 없는지 미리 체크해보기 위해 가상의 머지 커밋에서 CI를 돌려 패스 하는지 확인하는 것이 의도.
만약 병합된 커밋이 아니라 현재 HEAD 커밋으로 이동하고 싶을 땐, `ref` 에 HEAD의 sha 를 대입하여 체크아웃.
체크아웃은 shallow by default 이므로, 즉, 마지막 커밋만 가지고 있는데 `fetch-depth` 값을 조정하여 원하는 최신 커밋 개수를 가져올 수 있고, 전체를 가져오고 싶으면 `0`으로 세팅. `fetch-depth` 기본값은 `1`

```yaml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.event.pull_request.head.sha }}
    fetch-depth: 0
```

**Comment by x-0o0** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment

<img width="762" alt="스크린샷 2024-01-07 오전 2 15 11" src="https://github.com/ku-ring/ios-app/assets/53814741/bb09bc58-7bda-47ce-a19a-2a87da604533">

보면 GITHUB_REF 가 default branch 입니다. 
pull_request 브랜치에서 돌리려면 `pull_request_review_comment` 이벤트를 사용해야 합니다.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment

<img width="747" alt="스크린샷 2024-01-07 오전 2 16 38" src="https://github.com/ku-ring/ios-app/assets/53814741/62efe431-720b-4bb8-8ef5-a0c9273725e0">

```yml
on:
  pull_request_review_comment:
    types: [created, edited]
```
로 수정하고
```yml
- if: github.event.issue.pull_request && contains(github.event.comment.body, '/쿠링') && contains(github.event.comment.body, '패키지 테스트')
+ if: contains(github.event.comment.body, '/쿠링') && contains(github.event.comment.body, '패키지 테스트') 
```

조건문에서 `github.event.issue.pull_request` 조건을 제거 합니다. 나머지 조건의 경우 event 하위 프로퍼티 동일하기 때문에 변경할 필요 없습니다.

PR reviewer 가 리뷰 커멘트를 남겼을 경우에만 동작하게 됩니다.

**Comment by x-0o0** [comment]
관련 작업 커밋

https://github.com/ku-ring/ios-app/pull/87/commits/ddf207025e17c5e4084a741395a8633eda4b74f5

**Comment by lgvv** [comment]
👀 살펴보기

**Comment by x-0o0** [comment]
pull_request_review_comment 의 단점은 PR을 생성한 사람이 워크플로우를 트리거할 수 없다는 점입니다.

issue_comment 로 해결하기 위해 issue_comment 이벤트 시, PR 브랜치 최신 커밋(`HEAD`) 로 체크아웃 하는 방법에 대해서 리서치 하던 중 다음 답변을 발견하였고 이를 `develop/2.0.0` 에 반영할 예정

https://github.com/actions/checkout/issues/331#issuecomment-1438220926

```yml
- name: Checkout pull request 🏁
        uses: actions/checkout@v3 # v4로 적용예정
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
```
